// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltraBusAPI.Datas;

#nullable disable

namespace UltraBusAPI.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20250113230655_AddTicketTable")]
    partial class AddTicketTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UltraBusAPI.Datas.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatArrangement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeatCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EndStationId")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("StartStationId")
                        .HasColumnType("int");

                    b.Property<string>("Stations")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EndStationId");

                    b.HasIndex("StartStationId");

                    b.ToTable("BusRoutes");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRouteStation", b =>
                {
                    b.Property<int?>("BusRouteId")
                        .HasColumnType("int");

                    b.Property<int?>("BusStationId")
                        .HasColumnType("int");

                    b.HasKey("BusRouteId", "BusStationId");

                    b.HasIndex("BusStationId");

                    b.ToTable("BusRouteStations");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRouteTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BusId")
                        .HasColumnType("int");

                    b.Property<int?>("BusRouteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("BusRouteId");

                    b.ToTable("BusRouteTrips");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRouteTripDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int?>("BusRouteTripId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EndStationId")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SeatArrangement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatArrangementStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StartStationId")
                        .HasColumnType("int");

                    b.Property<string>("Stations")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusRouteTripId");

                    b.HasIndex("EndStationId");

                    b.HasIndex("StartStationId");

                    b.ToTable("BusRouteTripDates");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("WardId");

                    b.ToTable("BusStations");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.OTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("OTPs");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BusRouteTripDateId")
                        .HasColumnType("int");

                    b.Property<int?>("BusStationDownId")
                        .HasColumnType("int");

                    b.Property<int?>("BusStationUpId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivedAmount")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToTalSeats")
                        .HasColumnType("int");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusRouteTripDateId");

                    b.HasIndex("BusStationDownId");

                    b.HasIndex("BusStationUpId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WardId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DistrictId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRoute", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.BusStation", "EndStation")
                        .WithMany("EndBusRoutes")
                        .HasForeignKey("EndStationId");

                    b.HasOne("UltraBusAPI.Datas.BusStation", "StartStation")
                        .WithMany("StartBusRoutes")
                        .HasForeignKey("StartStationId");

                    b.Navigation("EndStation");

                    b.Navigation("StartStation");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRouteStation", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.BusRoute", "BusRoute")
                        .WithMany("BusRouteStations")
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltraBusAPI.Datas.BusStation", "BusStation")
                        .WithMany("BusRouteStations")
                        .HasForeignKey("BusStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("BusStation");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRouteTrip", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId");

                    b.HasOne("UltraBusAPI.Datas.BusRoute", "BusRoute")
                        .WithMany("BusRouteTrips")
                        .HasForeignKey("BusRouteId");

                    b.Navigation("Bus");

                    b.Navigation("BusRoute");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRouteTripDate", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.BusRouteTrip", "BusRouteTrip")
                        .WithMany("BusRouteTripDates")
                        .HasForeignKey("BusRouteTripId");

                    b.HasOne("UltraBusAPI.Datas.BusStation", "EndStation")
                        .WithMany("EndBusRouteTripDates")
                        .HasForeignKey("EndStationId");

                    b.HasOne("UltraBusAPI.Datas.BusStation", "StartStation")
                        .WithMany("StartBusRouteTripDates")
                        .HasForeignKey("StartStationId");

                    b.Navigation("BusRouteTrip");

                    b.Navigation("EndStation");

                    b.Navigation("StartStation");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusStation", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.District", "District")
                        .WithMany("BusStations")
                        .HasForeignKey("DistrictId");

                    b.HasOne("UltraBusAPI.Datas.Province", "Province")
                        .WithMany("BusStations")
                        .HasForeignKey("ProvinceId");

                    b.HasOne("UltraBusAPI.Datas.Ward", "Ward")
                        .WithMany("BusStations")
                        .HasForeignKey("WardId");

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.District", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.RolePermission", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltraBusAPI.Datas.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Ticket", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.BusRouteTripDate", "BusRouteTripDate")
                        .WithMany("Tickets")
                        .HasForeignKey("BusRouteTripDateId");

                    b.HasOne("UltraBusAPI.Datas.BusStation", "BusStationDown")
                        .WithMany("TicketsDown")
                        .HasForeignKey("BusStationDownId");

                    b.HasOne("UltraBusAPI.Datas.BusStation", "BusStationUp")
                        .WithMany("TicketsUp")
                        .HasForeignKey("BusStationUpId");

                    b.HasOne("UltraBusAPI.Datas.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId");

                    b.Navigation("BusRouteTripDate");

                    b.Navigation("BusStationDown");

                    b.Navigation("BusStationUp");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.User", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.District", "District")
                        .WithMany("Users")
                        .HasForeignKey("DistrictId");

                    b.HasOne("UltraBusAPI.Datas.Province", "Province")
                        .WithMany("Users")
                        .HasForeignKey("ProvinceId");

                    b.HasOne("UltraBusAPI.Datas.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.HasOne("UltraBusAPI.Datas.Ward", "Ward")
                        .WithMany("Users")
                        .HasForeignKey("WardId");

                    b.Navigation("District");

                    b.Navigation("Province");

                    b.Navigation("Role");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Ward", b =>
                {
                    b.HasOne("UltraBusAPI.Datas.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRoute", b =>
                {
                    b.Navigation("BusRouteStations");

                    b.Navigation("BusRouteTrips");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRouteTrip", b =>
                {
                    b.Navigation("BusRouteTripDates");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusRouteTripDate", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.BusStation", b =>
                {
                    b.Navigation("BusRouteStations");

                    b.Navigation("EndBusRouteTripDates");

                    b.Navigation("EndBusRoutes");

                    b.Navigation("StartBusRouteTripDates");

                    b.Navigation("StartBusRoutes");

                    b.Navigation("TicketsDown");

                    b.Navigation("TicketsUp");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.District", b =>
                {
                    b.Navigation("BusStations");

                    b.Navigation("Users");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Province", b =>
                {
                    b.Navigation("BusStations");

                    b.Navigation("Districts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.User", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("UltraBusAPI.Datas.Ward", b =>
                {
                    b.Navigation("BusStations");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
